### ISSUE TITLE
Add D2 as image generator for state machine

### ISSUE THREAD

**Issue by kuleshov-aleksei** [mikhail-barg/NiceStateMachineGenerator#10]
[D2 (diagram scripting language)](https://github.com/terrastruct/d2) became opensource and could be nice addition for output format for state machine generator

Here is a comparison with graphviz: https://text-to-diagram.com/?example=shapes&b=graphviz
By the way, there is a GUI editor, that supports bidirectional updates for generated graph https://youtu.be/EhxVVkxv2Ns?t=162 (2:40)

Propose: Add D2 as an option for output image generation

**Comment by mikhail-barg** [comment]
Great point, thanks!

There are some other diagramming engines to consider:
* [Mermaid](https://mermaid.js.org) supports [state diagrams](https://mermaid.js.org/syntax/stateDiagram.html)
* [PlantUML](https://plantuml.com/) also supports [state diagrams](https://plantuml.com/state-diagram)

**Comment by mikhail-barg** [comment]
docs are here https://d2lang.com/tour/intro/

**Comment by mikhail-barg** [comment]
Generally implemented support for D2, thanks for suggesting this!
